// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbRn1OZBzHvW7hTr8-lcMcs-nlU1Mqj94',
    appId: '1:129045767768:web:bbe0f221dda5101868cc2d',
    messagingSenderId: '129045767768',
    projectId: 'savefood-egypt',
    authDomain: 'savefood-egypt.firebaseapp.com',
    storageBucket: 'savefood-egypt.firebasestorage.app',
    measurementId: 'G-NBFF7TMR7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFrKYdz2tRH04lzBUYCwVVgepaR1BfDWQ',
    appId: '1:129045767768:android:143c00bdcf78de0d68cc2d',
    messagingSenderId: '129045767768',
    projectId: 'savefood-egypt',
    storageBucket: 'savefood-egypt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb_6KrhqP9gcua7_vEIdnNwvnnuKKQk-U',
    appId: '1:129045767768:ios:6287601edd0e0b7568cc2d',
    messagingSenderId: '129045767768',
    projectId: 'savefood-egypt',
    storageBucket: 'savefood-egypt.firebasestorage.app',
    iosBundleId: 'com.example.api',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb_6KrhqP9gcua7_vEIdnNwvnnuKKQk-U',
    appId: '1:129045767768:ios:6287601edd0e0b7568cc2d',
    messagingSenderId: '129045767768',
    projectId: 'savefood-egypt',
    storageBucket: 'savefood-egypt.firebasestorage.app',
    iosBundleId: 'com.example.api',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbRn1OZBzHvW7hTr8-lcMcs-nlU1Mqj94',
    appId: '1:129045767768:web:755a7c9875e4663768cc2d',
    messagingSenderId: '129045767768',
    projectId: 'savefood-egypt',
    authDomain: 'savefood-egypt.firebaseapp.com',
    storageBucket: 'savefood-egypt.firebasestorage.app',
    measurementId: 'G-96W16NL072',
  );
}
